### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Brendan-Leal** [Sentinel-PaaS/sentinel-api#44]
Solutions where implemented manually in the server as experiments.

- Immediately starting the application fails. The application is looking for an uploads directory
  - Solution created uploads folder in the root directory of `sentinel-api-2`
  - Note: Not sure why we are checking for this file on startup?
- POST `/api/cluster/initialize` fails
  - Solution: in the functions `initializeTerraform` and `applyTerraform` you forgot to preped the commands with sudo.
 
- With the above 2 fixes implemented POST `/api/cluster/initialize` fails again. 
  - You're attempting to run this command `chmod 400 ~/.ssh/managerKey.pem",` against a file that doesn't exist. `chmod: cannot access ‘/home/ec2-user/.ssh/managerKey.pem’: No such file or directory\n"` After getting this error I checked my key pairs and found one by this name `managerKey` I noticed the spelling of this key pair is different than the one declared in `mian.tf` `manager_kp`. Could this be the problem?

**Comment by dsessler7** [comment]
The uploads directory is for the `multer` package which is in place for receiving the sql file on app deploy when the app has a database. We should either include the uploads directory in the repo or we should set the directory that multer uses to another folder that already exists (or just set it to the api root folder).

Yeah i forgot sudo because if i include it on my machine it asks me for my password. I will change that...

In regards to the key pair... Is it in the ~/.ssh/ folder but it just doesn't have the .pem file extension in the filename?

**Comment by dsessler7** [comment]
Maybe it's an issue of the user not having permissions to create a key in the .ssh directory? I can change it so the keys are placed in the API directory...

**Comment by samlipari** [comment]
I'm not using multer anymore, express-fileupload was easier so I went with that and I will have an empty already created sql folder for it included with the repo
